### ISSUE TITLE
最中を磨く

### ISSUE THREAD

**Issue by keitakawamoto** [yusukesasaki-com/MonakaMailForm#34]
:tea:

@yusukesasaki-com といろいろお話しした結果、 http://web-dev.xyz/oss-sample/Monaka-1.2.2/mailform.php の見た目的品質・カスタマイズしやすさ向上のためのアドバイスをさせていただく。

**Comment by keitakawamoto** [comment]
## Todo

ここに追加していく

**Comment by keitakawamoto** [comment]
ここ以降で検討

**Comment by keitakawamoto** [comment]
## フォーカス

![image](https://cloud.githubusercontent.com/assets/1661325/17096505/a8911afa-5294-11e6-9208-1d11e18518bd.png)

フォーカスしたらブラウザのデフォルトスタイルがで起用されるので、色を変えやすそうなオリジナルのスタイルを指定しておくのはどうでしょう。

```
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
```

これでデフォルトスタイルを削除できます。

参考： http://codepen.io/keitakawamoto/pen/RRQPqV

**Comment by keitakawamoto** [comment]
## フォーム

![image](https://cloud.githubusercontent.com/assets/1661325/17096848/4ea973f0-5296-11e6-9fcc-fb6b9055f86b.png)

同系色でborderをつけて、シャドウを軽くかけると、「入力できる部分だ」ということを伝えやすくなりそうです。

```css
.mailform dd input[type="text"], .mailform dd select, dd textarea {
    width: 315px;
    max-width: 100%;
    font-family: inherit;
    padding: 7px 12px;
    font-size: 14px;
    background: #f4f4ff;
    border-radius: 4px;
    border: 1px solid #ddddea;
    box-shadow: inset 0 1px 2px rgba(0,0,0,.05);
}
```
